version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: install
          command: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - ./node_modules